.SILENT:
CASE := 1
test1:
	echo "In:";
	cat ./tests/sample-$(CASE).in;
	echo "Executed:"
	cat ./tests/sample-$(CASE).in | go run main.go;
	echo "Expected:";
	cat ./tests/sample-$(CASE).out
.SILENT:
CASE := 2
test2:
	echo "In:";
	cat ./tests/sample-$(CASE).in;
	echo "Executed:"
	cat ./tests/sample-$(CASE).in | go run main.go;
	echo "Expected:";
	cat ./tests/sample-$(CASE).out
.SILENT:
CASE := 3
test3:
	echo "In:";
	cat ./tests/sample-$(CASE).in;
	echo "Executed:"
	cat ./tests/sample-$(CASE).in | go run main.go;
	echo "Expected:";
	cat ./tests/sample-$(CASE).out
.SILENT:
CASE := 4
test4:
	echo "In:";
	cat ./tests/sample-$(CASE).in;
	echo "Executed:"
	cat ./tests/sample-$(CASE).in | go run main.go;
	echo "Expected:";
	cat ./tests/sample-$(CASE).out
